/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Yaksh Patel
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        historyTF = new javax.swing.JTextField();
        englishTF = new javax.swing.JTextField();
        physicsTF = new javax.swing.JTextField();
        hletterTF = new javax.swing.JTextField();
        mathTF = new javax.swing.JTextField();
        chemistryTF = new javax.swing.JTextField();
        eletterTF = new javax.swing.JTextField();
        mletterTF = new javax.swing.JTextField();
        pletterTF = new javax.swing.JTextField();
        cletterTF = new javax.swing.JTextField();
        averageTF = new javax.swing.JTextField();
        cgpaTF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("CGPA Calculator");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("History:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("English:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("   Math:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Physics:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Chemistry:");

        historyTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historyTFActionPerformed(evt);
            }
        });

        englishTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                englishTFActionPerformed(evt);
            }
        });

        physicsTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                physicsTFActionPerformed(evt);
            }
        });

        hletterTF.setEditable(false);
        hletterTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hletterTFActionPerformed(evt);
            }
        });

        mathTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mathTFActionPerformed(evt);
            }
        });

        chemistryTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chemistryTFActionPerformed(evt);
            }
        });

        eletterTF.setEditable(false);
        eletterTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eletterTFActionPerformed(evt);
            }
        });

        mletterTF.setEditable(false);
        mletterTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mletterTFActionPerformed(evt);
            }
        });

        pletterTF.setEditable(false);
        pletterTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pletterTFActionPerformed(evt);
            }
        });

        cletterTF.setEditable(false);
        cletterTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cletterTFActionPerformed(evt);
            }
        });

        averageTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                averageTFActionPerformed(evt);
            }
        });

        cgpaTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cgpaTFActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("CGPA");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Average");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Letter Grade");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Calculate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(32, 32, 32)
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(physicsTF, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(136, 136, 136)
                            .addComponent(chemistryTF, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(englishTF, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mathTF, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(historyTF, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(hletterTF, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pletterTF, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cletterTF, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(eletterTF, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mletterTF, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(averageTF, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cgpaTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(98, 98, 98))
            .addGroup(layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(237, 237, 237)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(historyTF, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(englishTF, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(mathTF, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(physicsTF, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(chemistryTF, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(hletterTF, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(eletterTF, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(37, 37, 37)
                                        .addComponent(mletterTF, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(35, 35, 35)
                                        .addComponent(pletterTF, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(averageTF, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cgpaTF, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(25, 25, 25)
                                .addComponent(cletterTF, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(183, 183, 183)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(131, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void historyTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historyTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_historyTFActionPerformed

    private void englishTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_englishTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_englishTFActionPerformed

    private void physicsTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_physicsTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_physicsTFActionPerformed

    private void hletterTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hletterTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hletterTFActionPerformed

    private void mathTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mathTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mathTFActionPerformed

    private void chemistryTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chemistryTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chemistryTFActionPerformed

    private void eletterTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eletterTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eletterTFActionPerformed

    private void mletterTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mletterTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mletterTFActionPerformed

    private void pletterTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pletterTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pletterTFActionPerformed

    private void cletterTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cletterTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cletterTFActionPerformed

    private void averageTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_averageTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_averageTFActionPerformed

    private void cgpaTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cgpaTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cgpaTFActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Calculate all the grades
        
        String historyScore, mathScore, englishScore, physicsScore, chemistryScore;
        double average; 
        double cgpa = 0;
        
        historyScore = historyTF.getText();
        mathScore= mathTF.getText();
        englishScore = englishTF.getText();
        physicsScore = physicsTF.getText();
        chemistryScore = chemistryTF.getText();
        
        double history = Double.parseDouble(historyScore);
        double math=Double.parseDouble(mathScore);
        double english = Double.parseDouble(englishScore);
        double physics = Double.parseDouble(physicsScore);
        double chemistry =Double.parseDouble(chemistryScore);
        
        average = (history + math + english + physics + chemistry)/5;
        
        if(history>=90){
            hletterTF.setText("A");
            cgpa = cgpa + 4.0;
            
        }
        else if(history>=80 && history<90){
              hletterTF.setText("B");
               cgpa = cgpa + 3.0;
            
        }
        else if(history>=70 && history<80){
              hletterTF.setText("C");
               cgpa = cgpa + 2.0;
            
        }
        else if(history>=60 && history<70){
              hletterTF.setText("D");
               cgpa = cgpa + 1.0;
            
        }
        else{
             hletterTF.setText("F");
              cgpa = cgpa + 0.0;
        }
        
        if(math>=90){
            mletterTF.setText("A");
            cgpa = cgpa + 4.0;
            
        }
        else if(math>=80 && math<90){
              mletterTF.setText("B");
               cgpa = cgpa + 3.0;
            
        }
        else if(math>=70 && math<80){
              mletterTF.setText("C");
               cgpa = cgpa + 2.0;
            
        }
        else if(math>=60 && math<70){
              mletterTF.setText("D");
               cgpa = cgpa + 1.0;
            
        }
        else{
             mletterTF.setText("F");
              cgpa = cgpa + 0.0;
        }
        
        if(english>=90){
            eletterTF.setText("A");
            cgpa = cgpa + 4.0;
            
        }
        else if(english>=80 && english<90){
              eletterTF.setText("B");
               cgpa = cgpa + 3.0;
            
        }
        else if(english>=70 && english<80){
              eletterTF.setText("C");
               cgpa = cgpa + 2.0;
            
        }
        else if(english>=60 && english<70){
              eletterTF.setText("D");
               cgpa = cgpa + 1.0;
            
        }
        else{
             eletterTF.setText("F");
              cgpa = cgpa + 0.0;
        }
        
        if(physics>=90){
            pletterTF.setText("A");
            cgpa = cgpa + 4.0;
            
        }
        else if(physics>=80 && physics<90){
              pletterTF.setText("B");
               cgpa = cgpa + 3.0;
            
        }
        else if(physics>=70 && physics<80){
              pletterTF.setText("C");
               cgpa = cgpa + 2.0;
            
        }
        else if(physics>=60 && physics<70){
              pletterTF.setText("D");
               cgpa = cgpa + 1.0;
            
        }
        else{
             pletterTF.setText("F");
              cgpa = cgpa + 0.0;
        }
        
        if(chemistry>=90){
            cletterTF.setText("A");
            cgpa = cgpa + 4.0;
            
        }
        else if(chemistry>=80 && chemistry<90){
              cletterTF.setText("B");
               cgpa = cgpa + 3.0;
            
        }
        else if(chemistry>=70 && chemistry<80){
              cletterTF.setText("C");
               cgpa = cgpa + 2.0;
            
        }
        else if(chemistry>=60 && chemistry<70){
              cletterTF.setText("D");
               cgpa = cgpa + 1.0;
            
        }
        else{
             cletterTF.setText("F");
              cgpa = cgpa + 0.0;
        }
        
        cgpa =cgpa/5;
        cgpaTF.setText(Double.toString(cgpa));
        averageTF.setText(Double.toString(average));
        
        
          
          
            
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField averageTF;
    private javax.swing.JTextField cgpaTF;
    private javax.swing.JTextField chemistryTF;
    private javax.swing.JTextField cletterTF;
    private javax.swing.JTextField eletterTF;
    private javax.swing.JTextField englishTF;
    private javax.swing.JTextField historyTF;
    private javax.swing.JTextField hletterTF;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField mathTF;
    private javax.swing.JTextField mletterTF;
    private javax.swing.JTextField physicsTF;
    private javax.swing.JTextField pletterTF;
    // End of variables declaration//GEN-END:variables
}
